# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0004_auto_20170426_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginevent',
            options={'ordering': ['-datetime'], 'verbose_name': 'Login event', 'verbose_name_plural': 'Login events'},
        ),
        migrations.AlterModelOptions(
            name='requestevent',
            options={'ordering': ['-datetime'], 'verbose_name': 'Request event', 'verbose_name_plural': 'Request events'},
        ),
        migrations.AddField(
            model_name='crudevent',
            name='remote_ip',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Remote IP'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='event_type',
            field=models.SmallIntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')], verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='object_id',
            field=models.IntegerField(verbose_name='Object id'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='object_json_repr',
            field=models.TextField(blank=True, null=True, verbose_name='Object json'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='user_pk_as_string',
            field=models.CharField(blank=True, help_text='String version of the user pk', max_length=255, null=True, verbose_name='User identifier'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='login_type',
            field=models.SmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Failed login')], verbose_name='Login type'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='remote_ip',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Remote IP'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='query_string',
            field=models.CharField(max_length=255, null=True, verbose_name='Query string'),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='remote_ip',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Remote IP'),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='type',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='uri',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Uri'),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
